version: '3.3'
services:
  kms:
    build: .
    container_name: kms
    env_file:
      - ./pro.env
    command: start
    volumes:
      - pseudo-kms:/data/pseudo-kms
    restart: unless-stopped
    depends_on:
      - kms_postgres
    ports:
      - "8080:80"
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kmsweb.rule=Host(`${PROXY_HOST}`)"
      - "traefik.http.routers.kmsweb.entrypoints=web"
    networks:
      - kms-net
      - proxy
  kms_postgres:
    container_name: kms_postgres
    image: postgres:15.1
    env_file:
      - ./pro.env
    volumes:
      - postgres-kms:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - kms-net
volumes:
  postgres-kms:
  pseudo-kms:
networks:
  proxy:
    external: true
  kms-net:
    external: false
